spring:
  profiles:
    active: default

---

spring:
  profiles: default
hono:
  server:
    bindaddress: 0.0.0.0
  downstream:
    host: qdrouter
    port: 5673
    name: hono-server

---

spring:
  profiles: activemq
hono:
  pathSeparator: .
  downstream:
    host: localhost
    port: 5671
    name: hono-server
